version: "3"
services:
  db:
    image: postgres:latest
    container_name: dong-nae-book-postgresDB
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./postgres/data:/var/lib/postgres